### ISSUE TITLE
Store namespace information within the refresh token

### ISSUE THREAD

**Issue by olibre** [synw/quid#3]
To generate a new `refresh_token` we provide three values:
* `namespace`
* `username`
* `password`

To request a new `access_token` we currently must provide the already known `namespace`:

```php
curl -X POST http://localhost:8082/token/access/10m           \
     -H 'Content-Type: application/json'                      \
     -d '{"refresh_token":"zpXVCJ9...", "namespace":"my_namespace"}'
```

If we store the namespace information within the `refresh_token`, we can simplify the `access_token` request:

```php
curl -X POST http://localhost:8082/token/access/10m           \
     -H 'Content-Type: application/json'                      \
     -d '{"refresh_token":"zpXVCJ9..."}'
```

**Comment by synw** [comment]
Right, this should be easier for the user. I will implement this

**Comment by synw** [comment]
Thinking about it I prefer leaving the namespace in the url. This because I need to retrieve the namespace key in the database to decode the refresh token. And for the server logs it is better to have this information
